In [1]:
import sys
from pathlib import Path

project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

print("Project root:", project_root)
print("Path added:", sys.path[-1])

Project root: c:\Users\melin\pipeline-decision-intelligence
Path added: c:\Users\melin\pipeline-decision-intelligence

In [ ]:
#Initial data checks for Sales Pipeline
from data.load_raw import load_csv

df = load_csv("sales_pipeline.csv")

df.head()
df.info()
df.describe()

""" Standard checks for each dataset
 df.info()
 df.describe()
 df.head(10)
 df.columns.tolist()
 df.isna().sum().sort_values(ascending=False)
 df.nunique().sort_values()

Check Key column uniqueness
df["opportunity_id"].nunique(), len(df) 

Inspect Categorical values
df["stage"].value_counts(dropna=False)
"""

Loaded sales_pipeline.csv
Shape: (8800, 8)
<class 'pandas.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  8800 non-null   str
 1   sales_agent     8800 non-null   str
 2   product         8800 non-null   str
 3   account         7375 non-null   str
 4   deal_stage      8800 non-null   str
 5   engage_date     8300 non-null   str
 6   close_date      6711 non-null   str
 7   close_value     6711 non-null   float64
dtypes: float64(1), str(7)
memory usage: 550.1 KB

' Standard checks for each dataset\n df.info()\n df.describe()\n df.head(10)\n df.columns.tolist()\n df.isna().sum().sort_values(ascending=False)\n df.nunique().sort_values()\n\nCheck Key column uniqueness\ndf["opportunity_id"].nunique(), len(df) \n\nInspect Categorical values\ndf["stage"].value_counts(dropna=False)\n'

In [12]:
df.head()

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517.0

In [13]:
df.columns.tolist()

['opportunity_id',
 'sales_agent',
 'product',
 'account',
 'deal_stage',
 'engage_date',
 'close_date',
 'close_value']

In [14]:
df.isna().sum().sort_values(ascending=False)

close_date        2089
close_value       2089
account           1425
engage_date        500
product              0
sales_agent          0
opportunity_id       0
deal_stage           0
dtype: int64

In [15]:
df.nunique().sort_values()

deal_stage           4
product              7
sales_agent         30
account             85
close_date         306
engage_date        421
close_value       2051
opportunity_id    8800
dtype: int64

In [16]:
df["opportunity_id"].nunique(), len(df)

(8800, 8800)

In [18]:
df["deal_stage"].value_counts(dropna=False)

deal_stage
Won            4238
Lost           2473
Engaging       1589
Prospecting     500
Name: count, dtype: int64

In [ ]:
from data.load_raw import load_csv

df = load_csv("accounts.csv")

df.head()
df.info()
df.describe()

""" Standard checks for each dataset
 df.info()
 df.describe()
 df.head(10)
 df.columns.tolist()
 df.isna().sum().sort_values(ascending=False)
 df.nunique().sort_values()

Check Key column uniqueness
df["opportunity_id"].nunique(), len(df) 

Inspect Categorical values
df["stage"].value_counts(dropna=False)
"""

Loaded accounts.csv
Shape: (85, 7)
<class 'pandas.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   account           85 non-null     str
 1   sector            85 non-null     str
 2   year_established  85 non-null     int64
 3   revenue           85 non-null     float64
 4   employees         85 non-null     int64
 5   office_location   85 non-null     str
 6   subsidiary_of     15 non-null     str
dtypes: float64(1), int64(2), str(4)
memory usage: 4.8 KB

' Standard checks for each dataset\n df.info()\n df.describe()\n df.head(10)\n df.columns.tolist()\n df.isna().sum().sort_values(ascending=False)\n df.nunique().sort_values()\n\nCheck Key column uniqueness\ndf["opportunity_id"].nunique(), len(df) \n\nInspect Categorical values\ndf["stage"].value_counts(dropna=False)\n'

In [20]:
 df.head(10)

,account,sector,year_established,revenue,employees,office_location,subsidiary_of
0,Acme Corporation,technolgy,1996,1100.04,2822,United States,NaN
1,Betasoloin,medical,1999,251.41,495,United States,NaN
2,Betatech,medical,1986,647.18,1185,Kenya,NaN
3,Bioholding,medical,2012,587.34,1356,Philipines,NaN
4,Bioplex,medical,1991,326.82,1016,United States,NaN
5,Blackzim,retail,2009,497.11,1588,United States,NaN
6,Bluth Company,technolgy,1993,1242.32,3027,United States,Acme Corporation
7,Bubba Gump,software,2002,987.39,2253,United States,NaN
8,Cancity,retail,2001,718.62,2448,United States,NaN
9,Cheers,entertainment,1993,4269.90,6472,United States,Massive Dynamic

In [21]:
df.columns.tolist()

['account',
 'sector',
 'year_established',
 'revenue',
 'employees',
 'office_location',
 'subsidiary_of']

In [22]:
df.isna().sum().sort_values(ascending=False)

subsidiary_of       70
sector               0
account              0
year_established     0
revenue              0
employees            0
office_location      0
dtype: int64

In [23]:
 df.nunique().sort_values()

subsidiary_of        7
sector              10
office_location     15
year_established    35
revenue             85
account             85
employees           85
dtype: int64

In [24]:
df["account"].nunique(), len(df)

(85, 85)

In [25]:
df["sector"].value_counts(dropna=False)

sector
retail                17
technolgy             12
medical               12
marketing              8
finance                8
software               7
entertainment          6
telecommunications     6
services               5
employment             4
Name: count, dtype: int64

In [26]:
df["office_location"].value_counts(dropna=False)

office_location
United States    71
Kenya             1
Philipines        1
Japan             1
Italy             1
Norway            1
Korea             1
Jordan            1
Brazil            1
Germany           1
Panama            1
Belgium           1
Romania           1
Poland            1
China             1
Name: count, dtype: int64

In [28]:
df["subsidiary_of"].value_counts(dropna=False)

subsidiary_of
NaN                 70
Acme Corporation     4
Sonron               3
Bubba Gump           2
Inity                2
Golddex              2
Massive Dynamic      1
Warephase            1
Name: count, dtype: int64

In [ ]:
from data.load_raw import load_csv

df = load_csv("metadata.csv")

df.head()
df.info()
df.describe()

""" Standard checks for each dataset
 df.info()
 df.describe()
 df.head(10)
 df.columns.tolist()
 df.isna().sum().sort_values(ascending=False)
 df.nunique().sort_values()

Check Key column uniqueness
df["opportunity_id"].nunique(), len(df) 

Inspect Categorical values
df["stage"].value_counts(dropna=False)
"""

Loaded metadata.csv
Shape: (21, 3)
<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Table        21 non-null     str
 1   Field        21 non-null     str
 2   Description  21 non-null     str
dtypes: str(3)
memory usage: 636.0 bytes

' Standard checks for each dataset\n df.info()\n df.describe()\n df.head(10)\n df.columns.tolist()\n df.isna().sum().sort_values(ascending=False)\n df.nunique().sort_values()\n\nCheck Key column uniqueness\ndf["opportunity_id"].nunique(), len(df) \n\nInspect Categorical values\ndf["stage"].value_counts(dropna=False)\n'

In [30]:
df.head()

      Table             Field                          Description
0  accounts           account                         Company name
1  accounts            sector                             Industry
2  accounts  year_established                     Year Established
3  accounts           revenue  Annual revenue (in millions of USD)
4  accounts         employees                  Number of employees

In [31]:
df

,Table,Field,Description
0,accounts,account,Company name
1,accounts,sector,Industry
2,accounts,year_established,Year Established
3,accounts,revenue,Annual revenue (in millions of USD)
4,accounts,employees,Number of employees
5,accounts,office_location,Headquarters
6,accounts,subsidiary_of,Parent company
7,products,product,Product name
8,products,series,Product series
9,products,sales_price,Suggested retail price
10,sales_teams,sales_agent,Sales agent
11,sales_teams,manager,Respective sales manager
12,sales_teams,regional_office,Regional office
13,sales_pipeline,opportunity_id,Unique identifier
14,sales_pipeline,sales_agent,Sales agent
15,sales_pipeline,product,Product name
16,sales_pipeline,account,Company name
17,sales_pipeline,deal_stage,Sales pipeline stage (Prospecting > Engaging >...
18,sales_pipeline,engage_date,"Date in which the ""Engaging"" deal stage was in..."
19,sales_pipeline,close_date,"Date in which the deal was ""Won"" or ""Lost"""
20,sales_pipeline,close_value,Revenue from the deal

In [ ]:
from data.load_raw import load_csv

df = load_csv("products.csv")

df.head()
df.info()
df.describe()

""" Standard checks for each dataset
 df.info()
 df.describe()
 df.head(10)
 df.columns.tolist()
 df.isna().sum().sort_values(ascending=False)
 df.nunique().sort_values()

Check Key column uniqueness
df["opportunity_id"].nunique(), len(df) 

Inspect Categorical values
df["stage"].value_counts(dropna=False)
"""

Loaded products.csv
Shape: (7, 3)
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product      7 non-null      str
 1   series       7 non-null      str
 2   sales_price  7 non-null      int64
dtypes: int64(1), str(2)
memory usage: 300.0 bytes

' Standard checks for each dataset\n df.info()\n df.describe()\n df.head(10)\n df.columns.tolist()\n df.isna().sum().sort_values(ascending=False)\n df.nunique().sort_values()\n\nCheck Key column uniqueness\ndf["opportunity_id"].nunique(), len(df) \n\nInspect Categorical values\ndf["stage"].value_counts(dropna=False)\n'

In [33]:
 df.head(10)

          product series  sales_price
0       GTX Basic    GTX          550
1         GTX Pro    GTX         4821
2      MG Special     MG           55
3     MG Advanced     MG         3393
4    GTX Plus Pro    GTX         5482
5  GTX Plus Basic    GTX         1096
6         GTK 500    GTK        26768

In [ ]:
from data.load_raw import load_csv

df = load_csv("sales_teams.csv")

df.head()
df.info()
df.describe()

Loaded sales_teams.csv
Shape: (35, 3)
<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sales_agent      35 non-null     str
 1   manager          35 non-null     str
 2   regional_office  35 non-null     str
dtypes: str(3)
memory usage: 972.0 bytes

          sales_agent        manager regional_office
count              35             35              35
unique             35              6               3
top     Anna Snelling  Melvin Marxen            East
freq                1              6              12

In [38]:
df.head(10)

          sales_agent           manager regional_office
0       Anna Snelling  Dustin Brinkmann         Central
1      Cecily Lampkin  Dustin Brinkmann         Central
2   Versie Hillebrand  Dustin Brinkmann         Central
3     Lajuana Vencill  Dustin Brinkmann         Central
4         Moses Frase  Dustin Brinkmann         Central
5  Jonathan Berthelot     Melvin Marxen         Central
6   Marty Freudenburg     Melvin Marxen         Central
7    Gladys Colclough     Melvin Marxen         Central
8     Niesha Huffines     Melvin Marxen         Central
9     Darcel Schlecht     Melvin Marxen         Central

In [43]:
df.columns.tolist()
df.isna().sum().sort_values(ascending=False)

df.nunique().sort_values()

regional_office     3
manager             6
sales_agent        35
dtype: int64

In [45]:
df["manager"].value_counts(dropna=False)

manager
Melvin Marxen       6
Cara Losch          6
Rocco Neubert       6
Celia Rouche        6
Summer Sewald       6
Dustin Brinkmann    5
Name: count, dtype: int64